### ISSUE TITLE
Run cron task to execute certificate renewal more frequently

### ISSUE THREAD

**Issue by hectcastro** [azavea/opendataphilly-ckan#97] opened 2019-03-25 16:37 UTC
Currently, the cron task to trigger certificate renewal is set to occur:

> At 23:00 on day-of-month 25.

Today, the certificate expired prior to the cron task running. A more frequent attempt to renew the certificate may have caught it. It is also possible that last months should have caught it, but didn't for some reason.

- [ ] Ensure cron jobs are working as expected
- [ ] Modify them so that they run more frequently

**Comment by KlaasH** [comment] 2021-02-08 13:58
For the 2/5/2021 warning, I tried running the renewal manually. I logged in, ran `crontab -l` as root, then ran the command from the second line:
```
certbot-auto renew --quiet --no-self-upgrade && service nginx reload
```
It did this:
> /opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a release (2.7.7+) that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,
Challenge failed for domain origin.opendataphilly.org
Attempting to renew cert (origin.opendataphilly.org) from /etc/letsencrypt/renewal/origin.opendataphilly.org.conf produced an unexpected error: Some challenges have failed.. Skipping.
The following certs could not be renewed:
  /etc/letsencrypt/live/origin.opendataphilly.org/fullchain.pem (failure)
1 renew failure(s), 0 parse failure(s)

I'm not sure what the problem is. The deprecation warning might be relevant, e.g. Let's Encrypt could have stopped answering requests from insecure Python 2.7 installations. Or the challenge could have failed for other reasons. Maybe the client is just too far out of date (possibly `--no-self-upgrade` isn't actually what we want in this case).

**Comment by coalkettler** [comment] 2021-02-08 19:52
> Attempting to renew cert (origin.opendataphilly.org) from /etc/letsencrypt/renewal/origin.opendataphilly.org.conf produced > an unexpected error: Some challenges have failed.. Skipping.
> The following certs could not be renewed:
> /etc/letsencrypt/live/origin.opendataphilly.org/fullchain.pem (failure)

This ended up being the problem. We had an old `origin.opendataphilly.org` certificate in there from when we needed to temporarily set up a CloudFront distribution to render the site read-only. Cleanup was tracked in https://github.com/azavea/operations/issues/538, but we didn't remove the origin certificate. Renewal attempts for that started to fail after the origin DNS record was removed. Things should proceed as normal now.

The default time to expiry for a renewal to occur is 30 days, so setting this to a 15 day cadence should resolve the case described in this issue and allow some time to respond in case something like this happens again. I'll submit a PR to get that fixed real quick and work with @KlaasH on a deploy. I'd prefer to get this knocked out while the config is still fresh in my head.

**Comment by hectcastro** [comment] 2021-02-08 21:56
My bad, all. :blush:

**Comment by coalkettler** [comment] 2021-02-08 22:57
@hectcastro Don't worry, we'll cover for ya 😜

**Comment by coalkettler** [comment] 2021-02-08 22:58
@KlaasH What's the deployment process look like? Is that something you'll be able to take on once #105 is merged? Not an immediate priority, new cert expires in three months.

**Comment by KlaasH** [comment] 2021-02-09 14:36
The deployment process documentation should be moved into a separate README in the `deployment/` directory and fleshed out, but it's basically what it says in [the README section](https://github.com/azavea/opendataphilly-ckan#deployment): spin up an EC2 instance by hand then point an `ansible-playbook` command at it.

Though also one thing that's missing from the instructions is that, as noted in [the 2.2->2.8 upgrade guide](https://github.com/azavea/opendataphilly-ckan/blob/develop/UPGRADING_2.2_TO_2.8.md#copy-uploaded-images-to-the-new-server-instance), there are some images stored on the server filesystem that need to be copied over to a new instance by hand.

It's not the most streamlined process, and given the small size of the change in PR #105 (+5/-1 characters, effectively), I think it's a good candidate for applying the change manually (i.e. with `crontab -e`) on the existing instance rather than spinning up a whole new one.

**Comment by coalkettler** [comment] 2021-02-10 23:12
@KlaasH Thank you! I talked this over with @rbreslow, we think we can knock out a release pretty quickly and will take responsibility for pushing out this change.

**Closed as completed** 2021-02-11 18:58 UTC
Labels: operations, size: 1, unplanned
